# fly.toml app configuration file generated for 3-1-3-8 on 2023-12-07T19:40:19+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "3-1-3-8"
primary_region = "syd"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
